; =============================================================================
; C-TRANSIT TERMINAL — PlatformIO Project Configuration
; Target : ESP32-WROOM-32E
; =============================================================================

[env:ctransit]
platform = espressif32 @ 6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Force LittleFS for better wear-leveling and crash resistance
board_build.filesystem = littlefs
board_build.partitions = partitions.csv

lib_deps =
    miguelbalboa/MFRC522 @ ^1.4.11
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    chris--a/Keypad @ ^3.1.1
    knolleary/PubSubClient @ ^2.8